export function getDom() {
  const byId = (id) => document.getElementById(id);
  return {
    statusText: byId("statusText"),
    debugText: byId("debugText"),

    cfgHome: byId("cfgHome"),
    watchHome: byId("watchHome"),
    autoStart: byId("autoStart"),
    translateMode: byId("translateMode"),
    notifySound: byId("notifySound"),
    followProc: byId("followProc"),
    onlyWhenProc: byId("onlyWhenProc"),
    procRegex: byId("procRegex"),
    maxSessions: byId("maxSessions"),
    replayLines: byId("replayLines"),
    includeAgent: byId("includeAgent"),
    pollInterval: byId("pollInterval"),
    scanInterval: byId("scanInterval"),

	    translatorSel: byId("translator"),
	    httpBlock: byId("httpBlock"),
	    nvidiaBlock: byId("nvidiaBlock"),
	    openaiBlock: byId("openaiBlock"),
	    nvidiaBaseUrl: byId("nvidiaBaseUrl"),
	    nvidiaModel: byId("nvidiaModel"),
	    nvidiaApiKey: byId("nvidiaApiKey"),
	    nvidiaAuthEnv: byId("nvidiaAuthEnv"),
	    nvidiaRpm: byId("nvidiaRpm"),
	    nvidiaTimeout: byId("nvidiaTimeout"),
	    openaiBaseUrl: byId("openaiBaseUrl"),
	    openaiModel: byId("openaiModel"),
	    openaiApiKey: byId("openaiApiKey"),
    openaiAuthMode: byId("openaiAuthMode"),
    openaiAuthEnv: byId("openaiAuthEnv"),
    openaiReasoning: byId("openaiReasoning"),
    openaiTimeout: byId("openaiTimeout"),
    httpProfile: byId("httpProfile"),
    httpProfileAddBtn: byId("httpProfileAddBtn"),
    httpProfileRenameBtn: byId("httpProfileRenameBtn"),
    httpProfileDelBtn: byId("httpProfileDelBtn"),
    httpUrl: byId("httpUrl"),
    httpToken: byId("httpToken"),
    httpTimeout: byId("httpTimeout"),
    httpAuthEnv: byId("httpAuthEnv"),

    saveBtn: byId("saveBtn"),
    recoverBtn: byId("recoverBtn"),

    startBtn: byId("startBtn"),
    stopBtn: byId("stopBtn"),
    restartBtn: byId("restartBtn"),
    clearBtn: byId("clearBtn"),
    configToggleBtn: byId("configToggleBtn"),
    quickViewBtn: byId("quickViewBtn"),
    translateToggleBtn: byId("translateToggleBtn"),
    drawerOverlay: byId("drawerOverlay"),
    drawer: byId("drawer"),
    drawerCloseBtn: byId("drawerCloseBtn"),
    shutdownBtn: byId("shutdownBtn"),
    scrollTopBtn: byId("scrollTopBtn"),
    scrollBottomBtn: byId("scrollBottomBtn"),

    tabs: byId("tabs"),
    pinOnSelect: byId("pinOnSelect"),
    exportThreadBtn: byId("exportThreadBtn"),
    hideThreadBtn: byId("hideThreadBtn"),
    showHiddenBtn: byId("showHiddenBtn"),
    list: byId("list"),
  };
}
