export function getDom() {
  const byId = (id) => document.getElementById(id);
  return {
    statusText: byId("statusText"),
    debugText: byId("debugText"),
    bookmarks: byId("bookmarks"),

    cfgHome: byId("cfgHome"),
    watchHome: byId("watchHome"),
	    autoStart: byId("autoStart"),
	    translateMode: byId("translateMode"),
	    notifySound: byId("notifySound"),
	    uiSkin: byId("uiSkin"),
	    followProc: byId("followProc"),
    onlyWhenProc: byId("onlyWhenProc"),
    procRegex: byId("procRegex"),
    maxSessions: byId("maxSessions"),
    replayLines: byId("replayLines"),
    pollInterval: byId("pollInterval"),
    scanInterval: byId("scanInterval"),

	    translatorSel: byId("translator"),
	    httpBlock: byId("httpBlock"),
	    nvidiaBlock: byId("nvidiaBlock"),
	    openaiBlock: byId("openaiBlock"),
	    saveTranslateBtn: byId("saveTranslateBtn"),
	    nvidiaBaseUrl: byId("nvidiaBaseUrl"),
	    nvidiaModel: byId("nvidiaModel"),
	    nvidiaApiKey: byId("nvidiaApiKey"),
	    nvidiaMaxTokens: byId("nvidiaMaxTokens"),
	    nvidiaRpm: byId("nvidiaRpm"),
	    nvidiaTimeout: byId("nvidiaTimeout"),
	    openaiBaseUrl: byId("openaiBaseUrl"),
	    openaiModel: byId("openaiModel"),
	    openaiApiKey: byId("openaiApiKey"),
    openaiAuthMode: byId("openaiAuthMode"),
    openaiReasoning: byId("openaiReasoning"),
    openaiTimeout: byId("openaiTimeout"),
    httpProfile: byId("httpProfile"),
    httpProfileAddBtn: byId("httpProfileAddBtn"),
    httpProfileRenameBtn: byId("httpProfileRenameBtn"),
    httpProfileDelBtn: byId("httpProfileDelBtn"),
    httpUrl: byId("httpUrl"),
    httpToken: byId("httpToken"),
    httpTimeout: byId("httpTimeout"),

    saveBtn: byId("saveBtn"),

    startBtn: byId("startBtn"),
    stopBtn: byId("stopBtn"),
    restartBtn: byId("restartBtn"),
    clearBtn: byId("clearBtn"),
    configToggleBtn: byId("configToggleBtn"),
    quickViewBtn: byId("quickViewBtn"),
    translateToggleBtn: byId("translateToggleBtn"),
    drawerOverlay: byId("drawerOverlay"),
    drawer: byId("drawer"),
    drawerCloseBtn: byId("drawerCloseBtn"),
    translateDrawerOverlay: byId("translateDrawerOverlay"),
    translateDrawer: byId("translateDrawer"),
    translateDrawerCloseBtn: byId("translateDrawerCloseBtn"),
    shutdownBtn: byId("shutdownBtn"),
    scrollTopBtn: byId("scrollTopBtn"),
    scrollBottomBtn: byId("scrollBottomBtn"),

    list: byId("list"),
  };
}
