export function getDom() {
  const byId = (id) => document.getElementById(id);
  return {
    statusText: byId("statusText"),
    statusMain: byId("statusMain"),
    statusHover: byId("statusHover"),
    debugText: byId("debugText"),
    bookmarks: byId("bookmarks"),

    cfgHome: byId("cfgHome"),
    watchHome: byId("watchHome"),
	    autoStart: byId("autoStart"),
	    translateMode: byId("translateMode"),
	    notifySound: byId("notifySound"),
	    uiSkin: byId("uiSkin"),
	    followProc: byId("followProc"),
    onlyWhenProc: byId("onlyWhenProc"),
    procRegex: byId("procRegex"),
    maxSessions: byId("maxSessions"),
    replayLines: byId("replayLines"),
    pollInterval: byId("pollInterval"),
    scanInterval: byId("scanInterval"),

	    translatorSel: byId("translator"),
	    httpBlock: byId("httpBlock"),
	    nvidiaBlock: byId("nvidiaBlock"),
	    openaiBlock: byId("openaiBlock"),
	    saveTranslateBtn: byId("saveTranslateBtn"),
	    translateErrorText: byId("translateErrorText"),
	    nvidiaBaseUrl: byId("nvidiaBaseUrl"),
	    nvidiaModel: byId("nvidiaModel"),
	    nvidiaApiKey: byId("nvidiaApiKey"),
	    nvidiaApiKeyEyeBtn: byId("nvidiaApiKeyEyeBtn"),
	    nvidiaMaxTokens: byId("nvidiaMaxTokens"),
	    nvidiaRpm: byId("nvidiaRpm"),
	    nvidiaTimeout: byId("nvidiaTimeout"),
	    openaiBaseUrl: byId("openaiBaseUrl"),
	    openaiBaseUrlEyeBtn: byId("openaiBaseUrlEyeBtn"),
	    openaiModel: byId("openaiModel"),
	    openaiApiKey: byId("openaiApiKey"),
	    openaiApiKeyEyeBtn: byId("openaiApiKeyEyeBtn"),
    openaiAuthMode: byId("openaiAuthMode"),
    openaiReasoning: byId("openaiReasoning"),
    openaiTimeout: byId("openaiTimeout"),
    httpProfile: byId("httpProfile"),
    httpProfileAddBtn: byId("httpProfileAddBtn"),
    httpProfileRenameBtn: byId("httpProfileRenameBtn"),
    httpProfileDelBtn: byId("httpProfileDelBtn"),
    httpUrl: byId("httpUrl"),
    httpToken: byId("httpToken"),
    httpTokenEyeBtn: byId("httpTokenEyeBtn"),
	    httpTimeout: byId("httpTimeout"),

	    saveBtn: byId("saveBtn"),
	    configErrorText: byId("configErrorText"),

	    clearBtn: byId("clearBtn"),
	    powerBtn: byId("powerBtn"),
	    configToggleBtn: byId("configToggleBtn"),
	    quickViewBtn: byId("quickViewBtn"),
	    translateToggleBtn: byId("translateToggleBtn"),
	    watchToggleBtn: byId("watchToggleBtn"),
	    drawerOverlay: byId("drawerOverlay"),
	    drawer: byId("drawer"),
	    drawerCloseBtn: byId("drawerCloseBtn"),
	    translateDrawerOverlay: byId("translateDrawerOverlay"),
    translateDrawer: byId("translateDrawer"),
    translateDrawerCloseBtn: byId("translateDrawerCloseBtn"),
    scrollTopBtn: byId("scrollTopBtn"),
    scrollBottomBtn: byId("scrollBottomBtn"),

    confirmDialog: byId("confirmDialog"),
    confirmDialogTitle: byId("confirmDialogTitle"),
    confirmDialogDesc: byId("confirmDialogDesc"),
    confirmDialogCancel: byId("confirmDialogCancel"),
    confirmDialogOk: byId("confirmDialogOk"),

    list: byId("list"),
  };
}
